name: Automatic Remote Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Prepare ssh keys
      uses: shimataro/ssh-key-action@v2.5.1
      with:
        key: ${{ secrets.CSCI312DEV_KEY }}
        known_hosts: ${{ secrets.CSCI312DEV_KNOWN_HOSTS }}

    - name: Checkout the Repo
      uses: actions/checkout@v3.5.2
      with:
        token: ${{ secrets.CSCI312DEV_KEY }}
        fetch-depth: 0
        ref: main

    - name: Push to csci312.dev
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git remote add deploy ssh://git@csci312.dev:ellen
        git push deploy



